export type EdgeModel = {
  id: string;
  name: string;
  logo: string;
};

export const edgeModelsSection = {
  title: "Models",
  body: "The Hailo model zoo Spectr Edge runs on the chip — detection, segmentation, pose, and the rest of the vision stack.",
};

export const edgeModels: EdgeModel[] = [
  { id: "yolov3", name: "YOLOv3", logo: "/images/models/yolov3.png" },
  { id: "yolov4", name: "YOLOv4", logo: "/images/models/yolov4.png" },
  { id: "yolov5", name: "YOLOv5", logo: "/images/models/yolov5.png" },
  { id: "yolov6", name: "YOLOv6", logo: "/images/models/yolov6.png" },
  { id: "yolov7", name: "YOLOv7", logo: "/images/models/yolov7.png" },
  { id: "yolov8", name: "YOLOv8", logo: "/images/models/yolov8.png" },
  { id: "yolov9", name: "YOLOv9", logo: "/images/models/yolov9.png" },
  { id: "yolov10", name: "YOLOv10", logo: "/images/models/yolov10.png" },
  { id: "yolo11", name: "YOLO11", logo: "/images/models/yolo11.png" },
  { id: "yolo12", name: "YOLO12", logo: "/images/models/yolo12.png" },
  { id: "yolo26", name: "YOLO26", logo: "/images/models/yolo26.png" },
  { id: "yolox", name: "YOLOX", logo: "/images/models/yolox.png" },
  { id: "damo-yolo", name: "DAMO-YOLO", logo: "/images/models/damo-yolo.png" },
  { id: "centernet", name: "CenterNet", logo: "/images/models/centernet.png" },
  { id: "detr", name: "DETR", logo: "/images/models/detr.png" },
  { id: "efficientdet", name: "EfficientDet", logo: "/images/models/efficientdet.png" },
  { id: "nanodet", name: "NanoDet", logo: "/images/models/nanodet.png" },
  { id: "ssd", name: "SSD", logo: "/images/models/ssd.png" },
  { id: "mobilenet", name: "MobileNet", logo: "/images/models/mobilenet.png" },
  { id: "resnet", name: "ResNet", logo: "/images/models/resnet.png" },
  { id: "efficientnet", name: "EfficientNet", logo: "/images/models/efficientnet.png" },
  { id: "vit", name: "ViT", logo: "/images/models/vit.png" },
  { id: "convnext", name: "ConvNeXt", logo: "/images/models/convnext.png" },
  { id: "swin", name: "Swin", logo: "/images/models/swin.png" },
  { id: "regnet", name: "RegNet", logo: "/images/models/regnet.png" },
  { id: "densenet", name: "DenseNet", logo: "/images/models/densenet.png" },
  { id: "deeplabv3", name: "DeepLabv3", logo: "/images/models/deeplabv3.png" },
  { id: "segformer", name: "SegFormer", logo: "/images/models/segformer.png" },
  { id: "unet", name: "U-Net", logo: "/images/models/unet.png" },
  { id: "yolact", name: "YOLACT", logo: "/images/models/yolact.png" },
  { id: "sparseinst", name: "SparseInst", logo: "/images/models/sparseinst.png" },
  { id: "yolov5-seg", name: "YOLOv5-seg", logo: "/images/models/yolov5-seg.png" },
  { id: "yolov8-seg", name: "YOLOv8-seg", logo: "/images/models/yolov8-seg.png" },
  { id: "fastsam", name: "FastSAM", logo: "/images/models/fastsam.png" },
  { id: "sam", name: "SAM", logo: "/images/models/sam.png" },
  { id: "clip", name: "CLIP", logo: "/images/models/clip.png" },
  { id: "openpose", name: "OpenPose", logo: "/images/models/openpose.png" },
  { id: "centerpose", name: "CenterPose", logo: "/images/models/centerpose.png" },
  { id: "yolov8-pose", name: "YOLOv8-pose", logo: "/images/models/yolov8-pose.png" },
  { id: "midas", name: "MiDaS", logo: "/images/models/midas.png" },
  { id: "depth-anything", name: "Depth Anything", logo: "/images/models/depth-anything.png" },
  { id: "retinaface", name: "RetinaFace", logo: "/images/models/retinaface.png" },
  { id: "scrfd", name: "SCRFD", logo: "/images/models/scrfd.png" },
  { id: "arcface", name: "ArcFace", logo: "/images/models/arcface.png" },
  { id: "osnet", name: "OSNet", logo: "/images/models/osnet.png" },
  { id: "whisper", name: "Whisper", logo: "/images/models/whisper.png" },
  { id: "paddleocr", name: "PaddleOCR", logo: "/images/models/paddleocr.png" },
  { id: "esrgan", name: "ESRGAN", logo: "/images/models/esrgan.png" },
];
