export type Integration = {
  id: string;
  name: string;
  logo: string;
  category: "cloud-erp-wms" | "industrial" | "sensors";
};

export const integrationsSection = {
  eyebrow: "Integrations",
  title: "The stack you already run.",
  body: "Spectr OS connects WMS, ERP, industrial controls, and sensors — from Google and SAP to Siemens, SensoTech, and the equipment on the floor.",
};

export const integrations: Integration[] = [
  { id: "google", name: "Google", logo: "/images/integrations/google.svg", category: "cloud-erp-wms" },
  { id: "google-cloud", name: "Google Cloud", logo: "/images/integrations/google-cloud.svg", category: "cloud-erp-wms" },
  { id: "sap", name: "SAP", logo: "/images/integrations/sap.svg", category: "cloud-erp-wms" },
  { id: "oracle", name: "Oracle", logo: "/images/integrations/oracle.svg", category: "cloud-erp-wms" },
  { id: "microsoft", name: "Microsoft", logo: "/images/integrations/microsoft.svg", category: "cloud-erp-wms" },
  { id: "microsoft-azure", name: "Microsoft Azure", logo: "/images/integrations/microsoft-azure.svg", category: "cloud-erp-wms" },
  { id: "ibm", name: "IBM", logo: "/images/integrations/ibm.svg", category: "cloud-erp-wms" },
  { id: "salesforce", name: "Salesforce", logo: "/images/integrations/salesforce.svg", category: "cloud-erp-wms" },
  { id: "aws", name: "Amazon Web Services", logo: "/images/integrations/aws.svg", category: "cloud-erp-wms" },
  { id: "snowflake", name: "Snowflake", logo: "/images/integrations/snowflake.svg", category: "cloud-erp-wms" },
  { id: "infor", name: "Infor", logo: "/images/integrations/infor.svg", category: "cloud-erp-wms" },
  { id: "epicor", name: "Epicor", logo: "/images/integrations/epicor.svg", category: "cloud-erp-wms" },
  { id: "sage", name: "Sage", logo: "/images/integrations/sage.svg", category: "cloud-erp-wms" },
  { id: "netsuite", name: "NetSuite", logo: "/images/integrations/netsuite.png", category: "cloud-erp-wms" },
  { id: "workday", name: "Workday", logo: "/images/integrations/workday.svg", category: "cloud-erp-wms" },
  { id: "odoo", name: "Odoo", logo: "/images/integrations/odoo.svg", category: "cloud-erp-wms" },
  { id: "ifs", name: "IFS", logo: "/images/integrations/ifs.png", category: "cloud-erp-wms" },
  { id: "unit4", name: "Unit4", logo: "/images/integrations/unit4.jpg", category: "cloud-erp-wms" },
  { id: "korber", name: "Körber", logo: "/images/integrations/korber.svg", category: "cloud-erp-wms" },
  { id: "blue-yonder", name: "Blue Yonder", logo: "/images/integrations/blue-yonder.png", category: "cloud-erp-wms" },
  { id: "kinaxis", name: "Kinaxis", logo: "/images/integrations/kinaxis.png", category: "cloud-erp-wms" },
  { id: "fishbowl", name: "Fishbowl", logo: "/images/integrations/fishbowl.png", category: "cloud-erp-wms" },
  { id: "siemens", name: "Siemens", logo: "/images/integrations/siemens.svg", category: "industrial" },
  { id: "rockwell", name: "Rockwell Automation", logo: "/images/integrations/rockwell.svg", category: "industrial" },
  { id: "schneider-electric", name: "Schneider Electric", logo: "/images/integrations/schneider-electric.svg", category: "industrial" },
  { id: "abb", name: "ABB", logo: "/images/integrations/abb.svg", category: "industrial" },
  { id: "honeywell", name: "Honeywell", logo: "/images/integrations/honeywell.svg", category: "industrial" },
  { id: "emerson", name: "Emerson", logo: "/images/integrations/emerson.svg", category: "industrial" },
  { id: "mitsubishi-electric", name: "Mitsubishi Electric", logo: "/images/integrations/mitsubishi-electric.svg", category: "industrial" },
  { id: "omron", name: "Omron", logo: "/images/integrations/omron.svg", category: "industrial" },
  { id: "fanuc", name: "FANUC", logo: "/images/integrations/fanuc.svg", category: "industrial" },
  { id: "kuka", name: "KUKA", logo: "/images/integrations/kuka.svg", category: "industrial" },
  { id: "yaskawa", name: "Yaskawa", logo: "/images/integrations/yaskawa.svg", category: "industrial" },
  { id: "bosch", name: "Bosch", logo: "/images/integrations/bosch.svg", category: "industrial" },
  { id: "phoenix-contact", name: "Phoenix Contact", logo: "/images/integrations/phoenix-contact.svg", category: "industrial" },
  { id: "beckhoff", name: "Beckhoff", logo: "/images/integrations/beckhoff.svg", category: "industrial" },
  { id: "ge", name: "GE", logo: "/images/integrations/ge.svg", category: "industrial" },
  { id: "yokogawa", name: "Yokogawa", logo: "/images/integrations/yokogawa.png", category: "industrial" },
  { id: "danfoss", name: "Danfoss", logo: "/images/integrations/danfoss.svg", category: "industrial" },
  { id: "festo", name: "Festo", logo: "/images/integrations/festo.svg", category: "industrial" },
  { id: "skf", name: "SKF", logo: "/images/integrations/skf.svg", category: "industrial" },
  { id: "atlas-copco", name: "Atlas Copco", logo: "/images/integrations/atlas-copco.svg", category: "industrial" },
  { id: "caterpillar", name: "Caterpillar", logo: "/images/integrations/caterpillar.svg", category: "industrial" },
  { id: "dematic", name: "Dematic", logo: "/images/integrations/dematic.png", category: "industrial" },
  { id: "swisslog", name: "Swisslog", logo: "/images/integrations/swisslog.svg", category: "industrial" },
  { id: "ssi-schaefer", name: "SSI SCHAEFER", logo: "/images/integrations/ssi-schaefer.svg", category: "industrial" },
  { id: "vanderlande", name: "Vanderlande", logo: "/images/integrations/vanderlande.jpg", category: "industrial" },
  { id: "knapp", name: "KNAPP", logo: "/images/integrations/knapp.svg", category: "industrial" },
  { id: "tgw", name: "TGW", logo: "/images/integrations/tgw.png", category: "industrial" },
  { id: "daifuku", name: "Daifuku", logo: "/images/integrations/daifuku.svg", category: "industrial" },
  { id: "kardex", name: "Kardex", logo: "/images/integrations/kardex.svg", category: "industrial" },
  { id: "sick", name: "SICK", logo: "/images/integrations/sick.svg", category: "sensors" },
  { id: "keyence", name: "Keyence", logo: "/images/integrations/keyence.svg", category: "sensors" },
  { id: "cognex", name: "Cognex", logo: "/images/integrations/cognex.svg", category: "sensors" },
  { id: "ifm", name: "ifm", logo: "/images/integrations/ifm.svg", category: "sensors" },
  { id: "pepperl-fuchs", name: "Pepperl+Fuchs", logo: "/images/integrations/pepperl-fuchs.svg", category: "sensors" },
  { id: "balluff", name: "Balluff", logo: "/images/integrations/balluff.svg", category: "sensors" },
  { id: "leuze", name: "Leuze", logo: "/images/integrations/leuze.svg", category: "sensors" },
  { id: "sensirion", name: "Sensirion", logo: "/images/integrations/sensirion.png", category: "sensors" },
  { id: "sensotech", name: "SensoTech", logo: "/images/integrations/sensotech.svg", category: "sensors" },
  { id: "fluke", name: "Fluke", logo: "/images/integrations/fluke.svg", category: "sensors" },
  { id: "te-connectivity", name: "TE Connectivity", logo: "/images/integrations/te-connectivity.svg", category: "sensors" },
  { id: "analog-devices", name: "Analog Devices", logo: "/images/integrations/analog-devices.svg", category: "sensors" },
  { id: "texas-instruments", name: "Texas Instruments", logo: "/images/integrations/texas-instruments.svg", category: "sensors" },
  { id: "panasonic", name: "Panasonic", logo: "/images/integrations/panasonic.svg", category: "sensors" },
  { id: "baumer", name: "Baumer", logo: "/images/integrations/baumer.svg", category: "sensors" },
  { id: "vega", name: "VEGA", logo: "/images/integrations/vega.svg", category: "sensors" },
  { id: "wika", name: "WIKA", logo: "/images/integrations/wika.svg", category: "sensors" },
  { id: "endress-hauser", name: "Endress+Hauser", logo: "/images/integrations/endress-hauser.jpg", category: "sensors" },
  { id: "datalogic", name: "Datalogic", logo: "/images/integrations/datalogic.svg", category: "sensors" },
  { id: "zebra", name: "Zebra", logo: "/images/integrations/zebra.svg", category: "sensors" },
  { id: "flir", name: "Teledyne FLIR", logo: "/images/integrations/flir.svg", category: "sensors" },
  { id: "axis", name: "Axis Communications", logo: "/images/integrations/axis.svg", category: "sensors" },
];
