export const spectrOsPage = {
  name: "Spectr OS",
  heroBody:
    "One operating system for industrial floors, warehouses, and enterprise sites. Free for enterprise customers — permanently.",
  heroImage: "/images/products/spectr-os-ui.png",
  heroImageAlt: "Spectr OS interface",
  introVideo: "/videos/spectr-os.mp4",
  featuresTitle: "What you can do on Spectr OS",
  features: [
    {
      id: "own-model",
      title: "Create your own model",
      body: "Build and align AI on your operation — not a generic foundation model. Train on your SKUs, flows, exceptions, and decisions so the system learns how your sites actually run.",
      image: "/images/bootcamp/step-2-train.png",
      imageAlt: "Training a model on operational data in Spectr OS",
    },
    {
      id: "ontology",
      title: "Ontology & agentic workflows",
      body: "Define the semantic layer of your world: objects, locations, actions, and relationships. Then run agents that propose, schedule, and execute work against that live model — with approvals, guardrails, and a full history of every action.",
      image: "/images/products/metaphysics-ui.png",
      imageAlt: "Ontology and agentic workflows in Spectr OS",
      video: "/videos/spectr-os-ontology.mp4",
    },
    {
      id: "data-hosting",
      title: "Data hosting",
      body: "Host operational data in the EU or on your own infrastructure. Your data stays yours — with governed access, retention, and audit from day one.",
      image: "/images/bootcamp/step-4-local.png",
      imageAlt: "Local and sovereign hosting for operational data",
    },
    {
      id: "data-fusion",
      title: "Data fusion",
      body: "Connect WMS, ERP, sensors, cameras, and spreadsheets into one live runtime. Spectr OS ranks what matters now — not what landed in yesterday’s report.",
      image: "/images/bootcamp/step-1-data.png",
      imageAlt: "Operational data fused from sensors and systems",
    },
    {
      id: "command",
      title: "Command & decisions",
      body: "Surface the next decision with context, evidence, and a clear recommend path. Humans stay in command; the OS removes the chase-down.",
      image: "/images/products/spectr-os-ui.png",
      imageAlt: "Spectr OS command surface with live decisions",
    },
    {
      id: "perception",
      title: "Perception on the floor",
      body: "See units, pallets, and exceptions in real time. Detections write into the same ontology your models and decisions already use.",
      image: "/spectr-detection.png",
      imageAlt: "Floor perception detecting units and exceptions",
    },
    {
      id: "apis",
      title: "APIs & integrations",
      body: "Open, API-first connections through REST and webhooks. Plug Spectr OS into the stack you already run without waiting on a roadmap.",
      image: "/images/bootcamp/step-5-operate.png",
      imageAlt: "Spectr OS operating with connected systems",
    },
    {
      id: "audit",
      title: "Audit & governance",
      body: "Full provenance for objects, model changes, and decisions. Built for regulated floors that need evidence, not screenshots.",
      image: "/images/login/spectr-aim-laptop.png",
      imageAlt: "Governed Spectr OS workspace with a full history of work",
    },
    {
      id: "deploy",
      title: "Deploy your way",
      body: "Self-host, edge, or cloud. Spectr OS is configuration on your aisle — not a science project that rebuilds the warehouse.",
      image: "/images/products/spectr-edge.jpg",
      imageAlt: "On-site and edge deployment of Spectr OS",
    },
  ],
  ctaTitle: "Run your enterprise on Spectr OS",
  ctaBody: "No licence fee, no user cap, no expiry date. Map where Spectr OS fits — in days, not quarters.",
  ctaImage: "/images/offerings/spectr-os.jpg",
  ctaImageAlt: "Industrial floor running on Spectr OS",
} as const;

export type SpectrOsFeature = (typeof spectrOsPage.features)[number];
