-- ============================================================
-- PARTS CATEGORIES SEED DATA
-- Run AFTER categories_schema.sql
-- Consolidated 3-level hierarchy: category -> subcategory -> part type
-- ============================================================

begin;

-- The category table is self-contained, so replace the old sprawling
-- taxonomy instead of leaving stale sections behind after upserts.
delete from public.categories;

-- ============================================================
-- LEVEL 1 - TOP SECTIONS
-- ============================================================
insert into public.categories (id, parent_id, name, slug, level, icon, sort_order) values
  (gen_random_uuid(), null, 'Engine & Performance', 'engine-performance', 1, '🔧', 10),
  (gen_random_uuid(), null, 'Cooling System', 'cooling-system', 1, '🌡️', 20),
  (gen_random_uuid(), null, 'Fuel & Exhaust', 'fuel-exhaust', 1, '⛽', 30),
  (gen_random_uuid(), null, 'Transmission & Drive', 'transmission-drive', 1, '⚙️', 40),
  (gen_random_uuid(), null, 'Suspension & Steering', 'suspension-steering', 1, '🔩', 50),
  (gen_random_uuid(), null, 'Braking System', 'braking-system', 1, '🛑', 60),
  (gen_random_uuid(), null, 'Wheels & Tyres', 'wheels-tyres', 1, '🏎️', 70),
  (gen_random_uuid(), null, 'Electrical & Ignition', 'electrical-ignition', 1, '⚡', 80),
  (gen_random_uuid(), null, 'Lighting', 'lighting', 1, '💡', 90),
  (gen_random_uuid(), null, 'Body, Interior & Accessories', 'body-interior-accessories', 1, '🚗', 100),
  (gen_random_uuid(), null, 'Service & Maintenance', 'service-maintenance', 1, '🛠️', 110);

-- ============================================================
-- LEVEL 2 - SUBCATEGORIES
-- ============================================================
insert into public.categories (id, parent_id, name, slug, level, sort_order)
select gen_random_uuid(), p.id, v.name, v.slug, 2, v.sort_order
from public.categories p
join (values
  ('engine-performance', 'Lubrication & Filters', 'lubrication-filters', 10),
  ('engine-performance', 'Internal Engine', 'internal-engine', 20),
  ('engine-performance', 'Timing & Belts', 'timing-belts', 30),
  ('engine-performance', 'Turbo, Intake & EGR', 'turbo-intake-egr', 40),
  ('engine-performance', 'Engine Mounts', 'engine-mounts', 50),
  ('cooling-system', 'Radiators & Cooling Fans', 'radiators-cooling-fans', 10),
  ('cooling-system', 'Pumps, Thermostats & Hoses', 'pumps-thermostats-hoses', 20),
  ('cooling-system', 'Heater & Coolant Components', 'heater-coolant-components', 30),
  ('fuel-exhaust', 'Fuel Delivery', 'fuel-delivery', 10),
  ('fuel-exhaust', 'Exhaust & Emissions', 'exhaust-emissions', 20),
  ('fuel-exhaust', 'Exhaust Sensors & Mounting', 'exhaust-sensors-mounting', 30),
  ('transmission-drive', 'Clutch System', 'clutch-system', 10),
  ('transmission-drive', 'Manual & Automatic Transmission', 'manual-automatic-transmission', 20),
  ('transmission-drive', 'CV Joints, Driveshafts & Axles', 'cv-driveshafts-axles', 30),
  ('transmission-drive', 'Differentials & Prop Shafts', 'differentials-prop-shafts', 40),
  ('suspension-steering', 'Front Suspension', 'front-suspension', 10),
  ('suspension-steering', 'Rear Suspension', 'rear-suspension', 20),
  ('suspension-steering', 'Steering', 'steering', 30),
  ('suspension-steering', 'Linkage & Joints', 'linkage-joints', 40),
  ('braking-system', 'Brake Discs, Drums & Pads', 'brake-discs-drums-pads', 10),
  ('braking-system', 'Brake Hydraulics', 'brake-hydraulics', 20),
  ('braking-system', 'Parking Brake', 'parking-brake', 30),
  ('braking-system', 'ABS & Brake Sensors', 'abs-brake-sensors', 40),
  ('wheels-tyres', 'Tyres', 'tyres', 10),
  ('wheels-tyres', 'Wheels', 'wheels', 20),
  ('wheels-tyres', 'Wheel Accessories & TPMS', 'wheel-accessories-tpms', 30),
  ('electrical-ignition', 'Ignition System', 'ignition-system', 10),
  ('electrical-ignition', 'Sensors', 'sensors', 20),
  ('electrical-ignition', 'Charging & Starting', 'charging-starting', 30),
  ('electrical-ignition', 'Wiring & Relays', 'wiring-relays', 40),
  ('electrical-ignition', 'Cameras & Driver Assistance', 'cameras-driver-assistance', 50),
  ('lighting', 'Headlights', 'headlights', 10),
  ('lighting', 'Rear Lights', 'rear-lights', 20),
  ('lighting', 'Interior Lighting', 'interior-lighting', 30),
  ('lighting', 'Bulbs & Controls', 'bulbs-controls', 40),
  ('body-interior-accessories', 'Exterior Trim & Panels', 'exterior-trim-panels', 10),
  ('body-interior-accessories', 'Glass, Seals & Wipers', 'glass-seals', 20),
  ('body-interior-accessories', 'Interior Trim', 'interior-trim', 30),
  ('body-interior-accessories', 'Comfort & Accessories', 'comfort-accessories', 40),
  ('body-interior-accessories', 'Air Conditioning', 'air-conditioning', 50),
  ('service-maintenance', 'Service Kits', 'service-kits', 10),
  ('service-maintenance', 'Oils & Fluids', 'oils-fluids', 20),
  ('service-maintenance', 'Greases, Additives & Treatments', 'greases-additives-treatments', 30),
  ('service-maintenance', 'Tools & Diagnostics', 'tools-diagnostics', 40)
) as v(parent_slug, name, slug, sort_order)
on p.slug = v.parent_slug;

-- ============================================================
-- LEVEL 3 - PART TYPES
-- ============================================================
insert into public.categories (id, parent_id, name, slug, level, sort_order)
select gen_random_uuid(), p.id, v.name, v.slug, 3, v.sort_order
from public.categories p
join (values
  ('lubrication-filters', 'Engine Oil', 'engine-oil', 10),
  ('lubrication-filters', 'Oil, Air & Fuel Filters', 'oil-air-fuel-filters', 20),
  ('lubrication-filters', 'Cabin & Interior Filters', 'cabin-interior-filters', 30),
  ('lubrication-filters', 'Hydraulic & Breather Filters', 'hydraulic-breather-filters', 40),
  ('internal-engine', 'Gaskets & Seals', 'gaskets-seals', 10),
  ('internal-engine', 'Valvetrain', 'valvetrain', 20),
  ('internal-engine', 'Pistons & Cylinders', 'pistons-cylinders', 30),
  ('internal-engine', 'Camshafts & VVT', 'camshafts-vvt', 40),
  ('timing-belts', 'Timing Belts & Chains', 'timing-belts-chains', 10),
  ('timing-belts', 'Timing Kits', 'timing-kits', 20),
  ('timing-belts', 'Drive Belts, Tensioners & Pulleys', 'drive-belts-tensioners-pulleys', 30),
  ('turbo-intake-egr', 'Turbochargers & Actuators', 'turbochargers-actuators', 10),
  ('turbo-intake-egr', 'Intercoolers & Boost Sensors', 'intercoolers-boost-sensors', 20),
  ('turbo-intake-egr', 'Throttle, Intake & PCV', 'throttle-intake-pcv', 30),
  ('turbo-intake-egr', 'EGR Valves & Coolers', 'egr-valves-coolers', 40),
  ('engine-mounts', 'Engine Mounts', 'engine-mount', 10),
  ('engine-mounts', 'Transmission Mounts', 'transmission-mount', 20),
  ('engine-mounts', 'Torque Rods & Dog Bone Mounts', 'torque-rods-dog-bone-mounts', 30),
  ('radiators-cooling-fans', 'Radiators & Intercoolers', 'radiators-intercoolers', 10),
  ('radiators-cooling-fans', 'Oil & EGR Coolers', 'oil-egr-coolers', 20),
  ('radiators-cooling-fans', 'Cooling Fans & Shrouds', 'cooling-fans-shrouds', 30),
  ('pumps-thermostats-hoses', 'Water Pumps', 'water-pumps', 10),
  ('pumps-thermostats-hoses', 'Thermostats & Housings', 'thermostats-housings', 20),
  ('pumps-thermostats-hoses', 'Coolant Hoses & Pipes', 'coolant-hoses-pipes', 30),
  ('heater-coolant-components', 'Heater Cores & Blowers', 'heater-cores-blowers', 10),
  ('heater-coolant-components', 'Expansion Tanks & Caps', 'expansion-tanks-caps', 20),
  ('heater-coolant-components', 'Coolant Valves & Sensors', 'coolant-valves-sensors', 30),
  ('fuel-delivery', 'Fuel Pumps', 'fuel-pumps', 10),
  ('fuel-delivery', 'Injectors, Rails & Regulators', 'injectors-rails-regulators', 20),
  ('fuel-delivery', 'Fuel Tanks, Caps & Senders', 'fuel-tanks-caps-senders', 30),
  ('fuel-delivery', 'Carburettors', 'carburettors', 40),
  ('exhaust-emissions', 'Catalytic Converters', 'catalytic-converters', 10),
  ('exhaust-emissions', 'DPF & SCR Systems', 'dpf-scr-systems', 20),
  ('exhaust-emissions', 'Pipes, Manifolds & Downpipes', 'pipes-manifolds-downpipes', 30),
  ('exhaust-emissions', 'Mufflers, Silencers & Tips', 'mufflers-silencers-tips', 40),
  ('exhaust-sensors-mounting', 'Lambda & Exhaust Temperature Sensors', 'lambda-exhaust-temperature-sensors', 10),
  ('exhaust-sensors-mounting', 'DPF Pressure Sensors', 'dpf-pressure-sensors', 20),
  ('exhaust-sensors-mounting', 'Clamps, Gaskets & Hangers', 'clamps-gaskets-hangers', 30),
  ('clutch-system', 'Clutch Kits & Plates', 'clutch-kits-plates', 10),
  ('clutch-system', 'Flywheels', 'flywheels', 20),
  ('clutch-system', 'Clutch Hydraulics & Cables', 'clutch-hydraulics-cables', 30),
  ('manual-automatic-transmission', 'Manual Gearbox Parts', 'manual-gearbox-parts', 10),
  ('manual-automatic-transmission', 'Automatic Gearbox & DSG Parts', 'automatic-gearbox-dsg-parts', 20),
  ('manual-automatic-transmission', 'Transmission Filters, Pans & Mounts', 'transmission-filters-pans-mounts', 30),
  ('cv-driveshafts-axles', 'Driveshafts & CV Axles', 'driveshafts-cv-axles', 10),
  ('cv-driveshafts-axles', 'CV Joints & Boots', 'cv-joints-boots', 20),
  ('cv-driveshafts-axles', 'Axles & Axle Seals', 'axles-axle-seals', 30),
  ('differentials-prop-shafts', 'Differentials', 'differentials', 10),
  ('differentials-prop-shafts', 'Prop Shafts', 'prop-shafts', 20),
  ('differentials-prop-shafts', 'Centre Bearings & Universal Joints', 'centre-bearings-universal-joints', 30),
  ('front-suspension', 'Front Shocks, Struts & Springs', 'front-shocks-struts-springs', 10),
  ('front-suspension', 'Front Control Arms & Wishbones', 'front-control-arms-wishbones', 20),
  ('front-suspension', 'Front Strut Mounts & Bearings', 'front-strut-mounts-bearings', 30),
  ('rear-suspension', 'Rear Shocks, Struts & Springs', 'rear-shocks-struts-springs', 10),
  ('rear-suspension', 'Rear Control & Trailing Arms', 'rear-control-trailing-arms', 20),
  ('rear-suspension', 'Rear Strut Mounts & Suspension Kits', 'rear-strut-mounts-suspension-kits', 30),
  ('steering', 'Steering Racks & Gaiters', 'steering-racks-gaiters', 10),
  ('steering', 'Power Steering Pumps & Hoses', 'power-steering-pumps-hoses', 20),
  ('steering', 'Columns, Shafts & EPS Motors', 'columns-shafts-eps-motors', 30),
  ('linkage-joints', 'Ball Joints & Tie Rods', 'ball-joints-tie-rods', 10),
  ('linkage-joints', 'Stabilizer Links & Anti-Roll Bars', 'stabilizer-links-anti-roll-bars', 20),
  ('linkage-joints', 'Bushings, Mounts & Wheel Hubs', 'bushings-mounts-wheel-hubs', 30),
  ('brake-discs-drums-pads', 'Brake Discs', 'brake-discs', 10),
  ('brake-discs-drums-pads', 'Brake Pads', 'brake-pads', 20),
  ('brake-discs-drums-pads', 'Brake Drums & Shoes', 'brake-drums-shoes', 30),
  ('brake-discs-drums-pads', 'Brake Calipers & Repair Kits', 'brake-calipers-repair-kits', 40),
  ('brake-hydraulics', 'Brake Lines, Pipes & Hoses', 'brake-lines-pipes-hoses', 10),
  ('brake-hydraulics', 'Master & Wheel Cylinders', 'master-wheel-cylinders', 20),
  ('brake-hydraulics', 'Brake Servos & Boosters', 'brake-servos-boosters', 30),
  ('parking-brake', 'Handbrake Cables', 'handbrake-cables', 10),
  ('parking-brake', 'Parking Brake Shoes', 'parking-brake-shoes', 20),
  ('parking-brake', 'Electric Parking Brake Actuators', 'electric-parking-brake-actuators', 30),
  ('abs-brake-sensors', 'ABS Wheel Speed Sensors', 'abs-wheel-speed-sensors', 10),
  ('abs-brake-sensors', 'ABS Rings & Modules', 'abs-rings-modules', 20),
  ('abs-brake-sensors', 'Brake Light Switches', 'brake-light-switches', 30),
  ('tyres', 'Summer, Winter & All-Season Tyres', 'summer-winter-all-season-tyres', 10),
  ('tyres', 'Run-Flat & Performance Tyres', 'run-flat-performance-tyres', 20),
  ('tyres', 'Commercial & Off-Road Tyres', 'commercial-off-road-tyres', 30),
  ('wheels', 'Alloy Wheels', 'alloy-wheels', 10),
  ('wheels', 'Steel Wheels', 'steel-wheels', 20),
  ('wheels', 'Winter Wheel Sets', 'winter-wheel-sets', 30),
  ('wheel-accessories-tpms', 'Wheel Bolts, Nuts & Lock Sets', 'wheel-bolts-nuts-lock-sets', 10),
  ('wheel-accessories-tpms', 'Spacers, Rings & Valve Stems', 'spacers-rings-valve-stems', 20),
  ('wheel-accessories-tpms', 'TPMS Sensors & Valves', 'tpms-sensors-valves', 30),
  ('ignition-system', 'Spark Plugs & Glow Plugs', 'spark-plugs-glow-plugs', 10),
  ('ignition-system', 'Ignition Coils & Leads', 'ignition-coils-leads', 20),
  ('ignition-system', 'Distributors & Ignition Modules', 'distributors-ignition-modules', 30),
  ('sensors', 'Engine Management Sensors', 'engine-management-sensors', 10),
  ('sensors', 'Temperature, Pressure & Knock Sensors', 'temperature-pressure-knock-sensors', 20),
  ('sensors', 'Switches & Position Sensors', 'switches-position-sensors', 30),
  ('charging-starting', 'Batteries & Terminals', 'batteries-terminals', 10),
  ('charging-starting', 'Alternators & Belts', 'alternators-belts', 20),
  ('charging-starting', 'Starter Motors & Solenoids', 'starter-motors-solenoids', 30),
  ('wiring-relays', 'Fuses & Fuse Boxes', 'fuses-fuse-boxes', 10),
  ('wiring-relays', 'Relays', 'relays', 20),
  ('wiring-relays', 'Wiring Looms & Harnesses', 'wiring-looms-harnesses', 30),
  ('cameras-driver-assistance', 'Reversing Cameras', 'reversing-cameras', 10),
  ('cameras-driver-assistance', 'Parking Sensors', 'parking-sensors', 20),
  ('cameras-driver-assistance', 'Driver Assistance Modules', 'driver-assistance-modules', 30),
  ('headlights', 'Headlight Assemblies', 'headlight-assemblies', 10),
  ('headlights', 'Fog Lights & DRLs', 'fog-lights-drls', 20),
  ('headlights', 'Headlight Washers & Levelling Motors', 'headlight-washers-levelling-motors', 30),
  ('rear-lights', 'Tail & Brake Lights', 'tail-brake-lights', 10),
  ('rear-lights', 'Reverse & Indicator Lights', 'reverse-indicator-lights', 20),
  ('rear-lights', 'Number Plate & High Mount Lights', 'number-plate-high-mount-lights', 30),
  ('interior-lighting', 'Dome, Courtesy & Reading Lights', 'dome-courtesy-reading-lights', 10),
  ('interior-lighting', 'Boot & Trunk Lights', 'boot-trunk-lights', 20),
  ('bulbs-controls', 'Halogen, HID & LED Bulbs', 'halogen-hid-led-bulbs', 10),
  ('bulbs-controls', 'Indicator & Wedge Bulbs', 'indicator-wedge-bulbs', 20),
  ('bulbs-controls', 'Light Switches & Control Units', 'light-switches-control-units', 30),
  ('exterior-trim-panels', 'Bumpers, Grilles & Brackets', 'bumpers-grilles-brackets', 10),
  ('exterior-trim-panels', 'Bonnets, Doors & Tailgates', 'bonnets-doors-tailgates', 20),
  ('exterior-trim-panels', 'Wings, Side Panels & Mirrors', 'wings-side-panels-mirrors', 30),
  ('exterior-trim-panels', 'Roof, Tow Bars & Paint Care', 'roof-tow-bars-paint-care', 40),
  ('glass-seals', 'Windscreens & Window Glass', 'windscreens-window-glass', 10),
  ('glass-seals', 'Window Seals & Regulators', 'window-seals-regulators', 20),
  ('glass-seals', 'Sunroof Glass & Mechanisms', 'sunroof-glass-mechanisms', 30),
  ('interior-trim', 'Seats, Upholstery & Seatbelts', 'seats-upholstery-seatbelts', 10),
  ('interior-trim', 'Dashboard, Console & Trim', 'dashboard-console-trim', 20),
  ('interior-trim', 'Pedals, Floor Mats & Gear Knobs', 'pedals-floor-mats-gear-knobs', 30),
  ('comfort-accessories', 'Door Handles & Locks', 'door-handles-locks', 10),
  ('comfort-accessories', 'Airbags & Clock Springs', 'airbags-clock-springs', 20),
  ('comfort-accessories', 'Interior Accessories', 'interior-accessories', 30),
  ('air-conditioning', 'AC Compressors & Clutches', 'ac-compressors-clutches', 10),
  ('air-conditioning', 'Condensers, Evaporators & Driers', 'condensers-evaporators-driers', 20),
  ('air-conditioning', 'AC Hoses, Valves & Pressure Switches', 'ac-hoses-valves-pressure-switches', 30),
  ('glass-seals', 'Wiper Blades, Arms & Linkages', 'wiper-blades-arms-linkages', 40),
  ('glass-seals', 'Wiper Motors', 'wiper-motors', 50),
  ('glass-seals', 'Washer Pumps, Jets & Reservoirs', 'washer-pumps-jets-reservoirs', 60),
  ('service-kits', 'Major & Minor Service Kits', 'major-minor-service-kits', 10),
  ('service-kits', 'Timing Service Kits', 'timing-service-kits', 20),
  ('service-kits', 'Brake Service Kits', 'brake-service-kits', 30),
  ('oils-fluids', 'Engine, Gear & Differential Oil', 'engine-gear-differential-oil', 10),
  ('oils-fluids', 'Brake, Steering & Transmission Fluids', 'brake-steering-transmission-fluids', 20),
  ('oils-fluids', 'Coolant & Antifreeze', 'coolant-antifreeze', 30),
  ('greases-additives-treatments', 'Greases & Spray Lubricants', 'greases-spray-lubricants', 10),
  ('greases-additives-treatments', 'Oil & Fuel Additives', 'oil-fuel-additives', 20),
  ('greases-additives-treatments', 'DPF, Injector & Coolant Treatments', 'dpf-injector-coolant-treatments', 30),
  ('tools-diagnostics', 'OBD2 & Battery Testers', 'obd2-battery-testers', 10),
  ('tools-diagnostics', 'Tyre Inflators & Compressors', 'tyre-inflators-compressors', 20),
  ('tools-diagnostics', 'Torque Wrenches, Jacks & Stands', 'torque-wrenches-jacks-stands', 30)
) as v(parent_slug, name, slug, sort_order)
on p.slug = v.parent_slug;

commit;
