-- ============================================================
-- PARTS CATEGORIES SEED DATA
-- Run AFTER categories_schema.sql
-- 3-level hierarchy: section -> group -> individual part type
-- ============================================================

-- ============================================================
-- LEVEL 1 — TOP SECTIONS
-- ============================================================
insert into public.categories (id, parent_id, name, slug, level, icon, sort_order) values
  (gen_random_uuid(), null, 'Engine', 'engine', 1, '🔧', 10),
  (gen_random_uuid(), null, 'Brakes & Stopping', 'brakes', 1, '🛑', 20),
  (gen_random_uuid(), null, 'Suspension & Steering', 'suspension-steering', 1, '🔩', 30),
  (gen_random_uuid(), null, 'Drivetrain & Transmission', 'drivetrain-transmission', 1, '⚙️', 40),
  (gen_random_uuid(), null, 'Electrical & Ignition', 'electrical-ignition', 1, '⚡', 50),
  (gen_random_uuid(), null, 'Exhaust System', 'exhaust', 1, '💨', 60),
  (gen_random_uuid(), null, 'Cooling & Heating', 'cooling-heating', 1, '🌡️', 70),
  (gen_random_uuid(), null, 'Fuel System', 'fuel-system', 1, '⛽', 80),
  (gen_random_uuid(), null, 'Filters', 'filters', 1, '🔲', 90),
  (gen_random_uuid(), null, 'Tyres & Wheels', 'tyres-wheels', 1, '🏎️', 100),
  (gen_random_uuid(), null, 'Lighting', 'lighting', 1, '💡', 110),
  (gen_random_uuid(), null, 'Wipers & Washers', 'wipers-washers', 1, '🌧️', 120),
  (gen_random_uuid(), null, 'Air Conditioning', 'air-conditioning', 1, '❄️', 130),
  (gen_random_uuid(), null, 'Body & Exterior', 'body-exterior', 1, '🚗', 140),
  (gen_random_uuid(), null, 'Interior & Comfort', 'interior-comfort', 1, '🪑', 150),
  (gen_random_uuid(), null, 'Service & Maintenance', 'service-maintenance', 1, '🛠️', 160)
on conflict (slug) do update set
  parent_id = excluded.parent_id,
  name = excluded.name,
  level = excluded.level,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  updated_at = now();

-- ============================================================
-- LEVEL 2 — GROUPS
-- ============================================================
insert into public.categories (id, parent_id, name, slug, level, sort_order)
select gen_random_uuid(), p.id, v.name, v.slug, 2, v.sort_order
from public.categories p
join (values
  ('engine', 'Engine Oil & Lubrication', 'engine-oil-lubrication', 10),
  ('engine', 'Filtration', 'engine-filtration', 20),
  ('engine', 'Timing & Drive Belts', 'timing-drive-belts', 30),
  ('engine', 'Gaskets & Seals', 'gaskets-seals', 40),
  ('engine', 'Valvetrain', 'valvetrain', 50),
  ('engine', 'Engine Mounts', 'engine-mounts', 60),
  ('engine', 'Pistons & Cylinders', 'pistons-cylinders', 70),
  ('engine', 'Turbocharger & Supercharger', 'turbo-supercharger', 80),
  ('engine', 'Intake & EGR', 'intake-egr', 90),
  ('brakes', 'Brake Discs', 'brake-discs', 10),
  ('brakes', 'Brake Pads', 'brake-pads', 20),
  ('brakes', 'Brake Drums & Shoes', 'brake-drums-shoes', 30),
  ('brakes', 'Brake Calipers', 'brake-calipers', 40),
  ('brakes', 'Brake Lines & Hoses', 'brake-lines-hoses', 50),
  ('brakes', 'Brake Master & Wheel Cylinders', 'brake-cylinders', 60),
  ('brakes', 'Handbrake & Parking Brake', 'handbrake-parking', 70),
  ('brakes', 'ABS & Sensors', 'abs-sensors', 80),
  ('suspension-steering', 'Shock Absorbers & Struts', 'shock-absorbers-struts', 10),
  ('suspension-steering', 'Coil Springs', 'coil-springs', 20),
  ('suspension-steering', 'Complete Spring & Shock Kits', 'spring-shock-kits', 30),
  ('suspension-steering', 'Strut Mounts & Bearings', 'strut-mounts-bearings', 40),
  ('suspension-steering', 'Control Arms & Wishbones', 'control-arms-wishbones', 50),
  ('suspension-steering', 'Ball Joints', 'ball-joints', 60),
  ('suspension-steering', 'Tie Rods & Track Rods', 'tie-rods-track-rods', 70),
  ('suspension-steering', 'Stabilizer Bars & Links', 'stabilizer-bars-links', 80),
  ('suspension-steering', 'Bushings & Mounts', 'bushings-mounts', 90),
  ('suspension-steering', 'Wheel Bearings & Hubs', 'wheel-bearings-hubs', 100),
  ('suspension-steering', 'Steering Rack & Gear', 'steering-rack-gear', 110),
  ('suspension-steering', 'Power Steering', 'power-steering', 120),
  ('suspension-steering', 'Steering Column & Shaft', 'steering-column-shaft', 130),
  ('drivetrain-transmission', 'Clutch System', 'clutch-system', 10),
  ('drivetrain-transmission', 'Gearbox & Manual Transmission', 'gearbox-manual', 20),
  ('drivetrain-transmission', 'Automatic Transmission', 'automatic-transmission', 30),
  ('drivetrain-transmission', 'CV Joints & Driveshafts', 'cv-joints-driveshafts', 40),
  ('drivetrain-transmission', 'Differential & Axles', 'differential-axles', 50),
  ('drivetrain-transmission', 'Propeller Shafts', 'propeller-shafts', 60),
  ('electrical-ignition', 'Batteries & Charging', 'batteries-charging', 10),
  ('electrical-ignition', 'Ignition System', 'ignition-system', 20),
  ('electrical-ignition', 'Starter & Alternator', 'starter-alternator', 30),
  ('electrical-ignition', 'Sensors & Switches', 'sensors-switches', 40),
  ('electrical-ignition', 'Fuses, Relays & Wiring', 'fuses-relays-wiring', 50),
  ('electrical-ignition', 'Cameras & Parking Sensors', 'cameras-parking-sensors', 60),
  ('exhaust', 'Catalytic Converters', 'catalytic-converters', 10),
  ('exhaust', 'DPF & SCR Systems', 'dpf-scr', 20),
  ('exhaust', 'Exhaust Pipes & Manifolds', 'exhaust-pipes-manifolds', 30),
  ('exhaust', 'Mufflers & Silencers', 'mufflers-silencers', 40),
  ('exhaust', 'Exhaust Sensors', 'exhaust-sensors', 50),
  ('exhaust', 'Exhaust Clamps & Hangers', 'exhaust-clamps-hangers', 60),
  ('cooling-heating', 'Radiators & Intercoolers', 'radiators-intercoolers', 10),
  ('cooling-heating', 'Cooling Fans & Shrouds', 'cooling-fans-shrouds', 20),
  ('cooling-heating', 'Water Pumps & Thermostats', 'water-pumps-thermostats', 30),
  ('cooling-heating', 'Coolant Hoses & Pipes', 'coolant-hoses-pipes', 40),
  ('cooling-heating', 'Heater Core & Blower', 'heater-core-blower', 50),
  ('fuel-system', 'Fuel Pumps', 'fuel-pumps', 10),
  ('fuel-system', 'Fuel Injectors & Rails', 'fuel-injectors-rails', 20),
  ('fuel-system', 'Fuel Tanks & Caps', 'fuel-tanks-caps', 30),
  ('fuel-system', 'Carburettors', 'carburettors', 40),
  ('fuel-system', 'Fuel Pressure Regulators', 'fuel-pressure-regulators', 50),
  ('filters', 'Engine Filters', 'engine-filters', 10),
  ('filters', 'Cabin & Interior Filters', 'cabin-interior-filters', 20),
  ('tyres-wheels', 'Tyres', 'tyres', 10),
  ('tyres-wheels', 'Alloy & Steel Wheels', 'alloy-steel-wheels', 20),
  ('tyres-wheels', 'Wheel Accessories', 'wheel-accessories', 30),
  ('tyres-wheels', 'Tyre Pressure (TPMS)', 'tpms', 40),
  ('lighting', 'Headlights & Front Lights', 'headlights-front-lights', 10),
  ('lighting', 'Rear Lights & Brake Lights', 'rear-brake-lights', 20),
  ('lighting', 'Interior Lighting', 'interior-lighting', 30),
  ('lighting', 'Bulbs', 'bulbs', 40),
  ('lighting', 'Light Control & Switches', 'light-control-switches', 50),
  ('wipers-washers', 'Wiper Blades', 'wiper-blades', 10),
  ('wipers-washers', 'Wiper Arms & Linkages', 'wiper-arms-linkages', 20),
  ('wipers-washers', 'Washer Pumps & Jets', 'washer-pumps-jets', 30),
  ('wipers-washers', 'Washer Fluid Reservoirs', 'washer-fluid-reservoirs', 40),
  ('air-conditioning', 'AC Compressors', 'ac-compressors', 10),
  ('air-conditioning', 'AC Condensers & Evaporators', 'ac-condensers-evaporators', 20),
  ('air-conditioning', 'AC Hoses & Valves', 'ac-hoses-valves', 30),
  ('air-conditioning', 'Cabin Air Filters', 'cabin-air-filters-ac', 40),
  ('body-exterior', 'Bumpers & Grilles', 'bumpers-grilles', 10),
  ('body-exterior', 'Bonnets & Doors', 'bonnets-doors', 20),
  ('body-exterior', 'Wings & Side Panels', 'wings-side-panels', 30),
  ('body-exterior', 'Mirrors', 'mirrors', 40),
  ('body-exterior', 'Glass & Seals', 'glass-seals', 50),
  ('body-exterior', 'Roof & Sunroof', 'roof-sunroof', 60),
  ('body-exterior', 'Tow Bars & Hitches', 'tow-bars-hitches', 70),
  ('body-exterior', 'Paint & Rustproofing', 'paint-rustproofing', 80),
  ('interior-comfort', 'Seats & Upholstery', 'seats-upholstery', 10),
  ('interior-comfort', 'Dashboard & Trim', 'dashboard-trim', 20),
  ('interior-comfort', 'Pedals & Floor Mats', 'pedals-floor-mats', 30),
  ('interior-comfort', 'Seatbelts & Airbags', 'seatbelts-airbags', 40),
  ('interior-comfort', 'Door Handles & Locks', 'door-handles-locks', 50),
  ('service-maintenance', 'Service Kits', 'service-kits', 10),
  ('service-maintenance', 'Engine Oil', 'engine-oil', 20),
  ('service-maintenance', 'Greases & Lubricants', 'greases-lubricants', 30),
  ('service-maintenance', 'Additives & Treatments', 'additives-treatments', 40),
  ('service-maintenance', 'Diagnostic Tools', 'diagnostic-tools', 50)
) as v(parent_slug, name, slug, sort_order)
on p.slug = v.parent_slug
on conflict (slug) do update set
  parent_id = excluded.parent_id,
  name = excluded.name,
  level = excluded.level,
  sort_order = excluded.sort_order,
  updated_at = now();

-- ============================================================
-- LEVEL 3 — INDIVIDUAL PART TYPES
-- ============================================================
insert into public.categories (id, parent_id, name, slug, level, sort_order)
select gen_random_uuid(), p.id, v.name, v.slug, 3, v.sort_order
from public.categories p
join (values
  ('engine-oil-lubrication', 'Engine Oil', 'engine-oil-product', 10),
  ('engine-oil-lubrication', 'Gear Oil', 'gear-oil', 20),
  ('engine-oil-lubrication', 'Differential Oil', 'differential-oil', 30),
  ('engine-oil-lubrication', 'Power Steering Fluid', 'power-steering-fluid', 40),
  ('engine-oil-lubrication', 'Brake Fluid', 'brake-fluid', 50),
  ('engine-oil-lubrication', 'Coolant / Antifreeze', 'coolant-antifreeze', 60),
  ('engine-filtration', 'Oil Filter', 'oil-filter', 10),
  ('engine-filtration', 'Air Filter', 'air-filter', 20),
  ('engine-filtration', 'Fuel Filter', 'fuel-filter', 30),
  ('engine-filtration', 'Hydraulic Filter', 'hydraulic-filter', 40),
  ('timing-drive-belts', 'Timing Belt', 'timing-belt', 10),
  ('timing-drive-belts', 'Timing Chain', 'timing-chain', 20),
  ('timing-drive-belts', 'Timing Belt Kit', 'timing-belt-kit', 30),
  ('timing-drive-belts', 'Timing Chain Kit', 'timing-chain-kit', 40),
  ('timing-drive-belts', 'Serpentine / Drive Belt', 'serpentine-drive-belt', 50),
  ('timing-drive-belts', 'Belt Tensioner', 'belt-tensioner', 60),
  ('timing-drive-belts', 'Belt Idler Pulley', 'belt-idler-pulley', 70),
  ('timing-drive-belts', 'Water Pump + Timing Belt Kit', 'water-pump-timing-kit', 80),
  ('gaskets-seals', 'Head Gasket', 'head-gasket', 10),
  ('gaskets-seals', 'Head Gasket Set', 'head-gasket-set', 20),
  ('gaskets-seals', 'Engine Gasket Set (Full)', 'engine-gasket-set-full', 30),
  ('gaskets-seals', 'Valve Cover Gasket', 'valve-cover-gasket', 40),
  ('gaskets-seals', 'Crankshaft Seal', 'crankshaft-seal', 50),
  ('gaskets-seals', 'Camshaft Seal', 'camshaft-seal', 60),
  ('gaskets-seals', 'Exhaust Manifold Gasket', 'exhaust-manifold-gasket', 70),
  ('gaskets-seals', 'Intake Manifold Gasket', 'intake-manifold-gasket', 80),
  ('gaskets-seals', 'Oil Sump Gasket', 'oil-sump-gasket', 90),
  ('gaskets-seals', 'O-Rings & Sealing Sets', 'o-rings-sealing-sets', 100),
  ('valvetrain', 'Rocker Arms', 'rocker-arms', 10),
  ('valvetrain', 'Valve Springs', 'valve-springs', 20),
  ('valvetrain', 'Camshaft', 'camshaft', 30),
  ('valvetrain', 'Variable Valve Timing (VVT) Unit', 'vvt-unit', 40),
  ('valvetrain', 'Hydraulic Lifter / Tappet', 'hydraulic-lifter-tappet', 50),
  ('engine-mounts', 'Engine Mount', 'engine-mount', 10),
  ('engine-mounts', 'Transmission Mount', 'transmission-mount', 20),
  ('engine-mounts', 'Torque Rod / Dog Bone Mount', 'torque-rod-dog-bone-mount', 30),
  ('pistons-cylinders', 'Piston', 'piston', 10),
  ('pistons-cylinders', 'Piston Ring Set', 'piston-ring-set', 20),
  ('pistons-cylinders', 'Cylinder Liner / Sleeve', 'cylinder-liner-sleeve', 30),
  ('turbo-supercharger', 'Turbocharger', 'turbocharger', 10),
  ('turbo-supercharger', 'Turbo Actuator', 'turbo-actuator', 20),
  ('turbo-supercharger', 'Intercooler', 'intercooler', 30),
  ('turbo-supercharger', 'Boost Pressure Sensor', 'boost-pressure-sensor', 40),
  ('intake-egr', 'Throttle Body', 'throttle-body', 10),
  ('intake-egr', 'Intake Manifold', 'intake-manifold', 20),
  ('intake-egr', 'EGR Valve', 'egr-valve', 30),
  ('intake-egr', 'EGR Cooler', 'egr-cooler', 40),
  ('intake-egr', 'Swirl Flap / Intake Flap', 'swirl-flap-intake-flap', 50),
  ('intake-egr', 'PCV Valve / Breather', 'pcv-valve-breather', 60),
  ('brake-discs', 'Front Brake Disc', 'front-brake-disc', 10),
  ('brake-discs', 'Rear Brake Disc', 'rear-brake-disc', 20),
  ('brake-discs', 'Sport Brake Disc (Drilled/Slotted)', 'sport-brake-disc', 30),
  ('brake-pads', 'Front Brake Pads', 'front-brake-pads', 10),
  ('brake-pads', 'Rear Brake Pads', 'rear-brake-pads', 20),
  ('brake-pads', 'Performance Brake Pads', 'performance-brake-pads', 30),
  ('brake-drums-shoes', 'Brake Drum', 'brake-drum', 10),
  ('brake-drums-shoes', 'Brake Shoes', 'brake-shoes', 20),
  ('brake-calipers', 'Front Brake Caliper', 'front-brake-caliper', 10),
  ('brake-calipers', 'Rear Brake Caliper', 'rear-brake-caliper', 20),
  ('brake-calipers', 'Caliper Repair Kit', 'caliper-repair-kit', 30),
  ('brake-lines-hoses', 'Brake Hose', 'brake-hose', 10),
  ('brake-lines-hoses', 'Brake Pipe / Hard Line', 'brake-pipe-hard-line', 20),
  ('brake-lines-hoses', 'Brake Line Kit', 'brake-line-kit', 30),
  ('brake-cylinders', 'Brake Master Cylinder', 'brake-master-cylinder', 10),
  ('brake-cylinders', 'Wheel Cylinder', 'wheel-cylinder', 20),
  ('brake-cylinders', 'Brake Servo / Booster', 'brake-servo-booster', 30),
  ('handbrake-parking', 'Handbrake Cable', 'handbrake-cable', 10),
  ('handbrake-parking', 'Electric Parking Brake Actuator', 'electric-parking-brake', 20),
  ('handbrake-parking', 'Parking Brake Shoes', 'parking-brake-shoes', 30),
  ('abs-sensors', 'ABS Wheel Speed Sensor', 'abs-wheel-speed-sensor', 10),
  ('abs-sensors', 'ABS Sensor Ring / Tone Ring', 'abs-sensor-ring', 20),
  ('abs-sensors', 'ABS Control Module', 'abs-control-module', 30),
  ('shock-absorbers-struts', 'Front Shock Absorber', 'front-shock-absorber', 10),
  ('shock-absorbers-struts', 'Rear Shock Absorber', 'rear-shock-absorber', 20),
  ('shock-absorbers-struts', 'Front Strut Assembly', 'front-strut-assembly', 30),
  ('shock-absorbers-struts', 'Rear Strut Assembly', 'rear-strut-assembly', 40),
  ('shock-absorbers-struts', 'Sport / Lowering Shock', 'sport-lowering-shock', 50),
  ('shock-absorbers-struts', 'Air Suspension Strut', 'air-suspension-strut', 60),
  ('coil-springs', 'Front Coil Spring', 'front-coil-spring', 10),
  ('coil-springs', 'Rear Coil Spring', 'rear-coil-spring', 20),
  ('coil-springs', 'Lowering Spring', 'lowering-spring', 30),
  ('coil-springs', 'Heavy-Duty / Sport Spring', 'heavy-duty-sport-spring', 40),
  ('spring-shock-kits', 'Front Suspension Kit', 'front-suspension-kit', 10),
  ('spring-shock-kits', 'Full Suspension Kit (4x)', 'full-suspension-kit', 20),
  ('spring-shock-kits', 'Coilover Kit', 'coilover-kit', 30),
  ('strut-mounts-bearings', 'Front Strut Top Mount', 'front-strut-top-mount', 10),
  ('strut-mounts-bearings', 'Rear Strut Top Mount', 'rear-strut-top-mount', 20),
  ('strut-mounts-bearings', 'Strut Bearing / Thrust Bearing', 'strut-bearing', 30),
  ('strut-mounts-bearings', 'Bump Stop / Jounce Buffer', 'bump-stop-jounce-buffer', 40),
  ('strut-mounts-bearings', 'Dust Boot / Gaiter', 'dust-boot-gaiter', 50),
  ('control-arms-wishbones', 'Front Upper Control Arm', 'front-upper-control-arm', 10),
  ('control-arms-wishbones', 'Front Lower Control Arm', 'front-lower-control-arm', 20),
  ('control-arms-wishbones', 'Rear Upper Control Arm', 'rear-upper-control-arm', 30),
  ('control-arms-wishbones', 'Rear Lower Control Arm', 'rear-lower-control-arm', 40),
  ('control-arms-wishbones', 'Trailing Arm', 'trailing-arm', 50),
  ('control-arms-wishbones', 'Wishbone Kit (with bushings)', 'wishbone-kit', 60),
  ('ball-joints', 'Front Upper Ball Joint', 'front-upper-ball-joint', 10),
  ('ball-joints', 'Front Lower Ball Joint', 'front-lower-ball-joint', 20),
  ('ball-joints', 'Rear Ball Joint', 'rear-ball-joint', 30),
  ('tie-rods-track-rods', 'Inner Tie Rod / Rack End', 'inner-tie-rod-rack-end', 10),
  ('tie-rods-track-rods', 'Outer Tie Rod End', 'outer-tie-rod-end', 20),
  ('tie-rods-track-rods', 'Tie Rod Assembly', 'tie-rod-assembly', 30),
  ('stabilizer-bars-links', 'Front Stabilizer Link / Drop Link', 'front-stabilizer-link', 10),
  ('stabilizer-bars-links', 'Rear Stabilizer Link / Drop Link', 'rear-stabilizer-link', 20),
  ('stabilizer-bars-links', 'Front Anti-Roll Bar', 'front-anti-roll-bar', 30),
  ('stabilizer-bars-links', 'Rear Anti-Roll Bar', 'rear-anti-roll-bar', 40),
  ('stabilizer-bars-links', 'Anti-Roll Bar Bushing', 'anti-roll-bar-bushing', 50),
  ('stabilizer-bars-links', 'Anti-Roll Bar Bracket', 'anti-roll-bar-bracket', 60),
  ('bushings-mounts', 'Front Subframe Bush', 'front-subframe-bush', 10),
  ('bushings-mounts', 'Rear Subframe Bush', 'rear-subframe-bush', 20),
  ('bushings-mounts', 'Control Arm Bushing', 'control-arm-bushing', 30),
  ('bushings-mounts', 'Trailing Arm Bushing', 'trailing-arm-bushing', 40),
  ('bushings-mounts', 'Differential Bush', 'differential-bush', 50),
  ('wheel-bearings-hubs', 'Front Wheel Bearing', 'front-wheel-bearing', 10),
  ('wheel-bearings-hubs', 'Rear Wheel Bearing', 'rear-wheel-bearing', 20),
  ('wheel-bearings-hubs', 'Front Wheel Hub Assembly', 'front-wheel-hub-assembly', 30),
  ('wheel-bearings-hubs', 'Rear Wheel Hub Assembly', 'rear-wheel-hub-assembly', 40),
  ('steering-rack-gear', 'Steering Rack', 'steering-rack', 10),
  ('steering-rack-gear', 'Steering Rack Gaiter / Boot', 'steering-rack-gaiter', 20),
  ('steering-rack-gear', 'Steering Damper', 'steering-damper', 30),
  ('power-steering', 'Power Steering Pump', 'power-steering-pump', 10),
  ('power-steering', 'Power Steering Reservoir', 'power-steering-reservoir', 20),
  ('power-steering', 'Power Steering Hose', 'power-steering-hose', 30),
  ('power-steering', 'Electric Power Steering Motor (EPS)', 'eps-motor', 40),
  ('steering-column-shaft', 'Steering Column', 'steering-column', 10),
  ('steering-column-shaft', 'Steering Shaft / Intermediate Shaft', 'steering-shaft', 20),
  ('steering-column-shaft', 'Steering Universal Joint', 'steering-universal-joint', 30),
  ('clutch-system', 'Clutch Kit (3-piece)', 'clutch-kit', 10),
  ('clutch-system', 'Clutch Disc / Friction Plate', 'clutch-disc', 20),
  ('clutch-system', 'Pressure Plate', 'pressure-plate', 30),
  ('clutch-system', 'Flywheel', 'flywheel', 40),
  ('clutch-system', 'Dual Mass Flywheel (DMF)', 'dual-mass-flywheel', 50),
  ('clutch-system', 'Release Bearing / Slave Cylinder', 'release-bearing-slave-cyl', 60),
  ('clutch-system', 'Clutch Master Cylinder', 'clutch-master-cylinder', 70),
  ('clutch-system', 'Clutch Cable', 'clutch-cable', 80),
  ('clutch-system', 'Clutch Fork / Lever', 'clutch-fork-lever', 90),
  ('gearbox-manual', 'Gearbox / Manual Transmission', 'gearbox-manual-transmission', 10),
  ('gearbox-manual', 'Gearbox Mount', 'gearbox-mount', 20),
  ('gearbox-manual', 'Gear Selector / Shift Rod', 'gear-selector-shift-rod', 30),
  ('gearbox-manual', 'Gear Linkage Bush', 'gear-linkage-bush', 40),
  ('automatic-transmission', 'Automatic Gearbox / DSG', 'automatic-gearbox-dsg', 10),
  ('automatic-transmission', 'Torque Converter', 'torque-converter', 20),
  ('automatic-transmission', 'Transmission Oil Pan', 'transmission-oil-pan', 30),
  ('automatic-transmission', 'ATF Filter', 'atf-filter', 40),
  ('cv-joints-driveshafts', 'Front Driveshaft / CV Axle', 'front-driveshaft-cv-axle', 10),
  ('cv-joints-driveshafts', 'Rear Driveshaft / CV Axle', 'rear-driveshaft-cv-axle', 20),
  ('cv-joints-driveshafts', 'Inner CV Joint', 'inner-cv-joint', 30),
  ('cv-joints-driveshafts', 'Outer CV Joint', 'outer-cv-joint', 40),
  ('cv-joints-driveshafts', 'CV Boot / Gaiter Kit', 'cv-boot-gaiter-kit', 50),
  ('differential-axles', 'Rear Axle Shaft', 'rear-axle-shaft', 10),
  ('differential-axles', 'Differential', 'differential', 20),
  ('differential-axles', 'Axle Seal', 'axle-seal', 30),
  ('propeller-shafts', 'Propeller Shaft / Prop Shaft', 'propeller-shaft', 10),
  ('propeller-shafts', 'Centre Support Bearing', 'centre-support-bearing', 20),
  ('propeller-shafts', 'Universal Joint (UJ)', 'universal-joint', 30),
  ('batteries-charging', 'Car Battery', 'car-battery', 10),
  ('batteries-charging', 'Alternator', 'alternator', 20),
  ('batteries-charging', 'Alternator Belt', 'alternator-belt', 30),
  ('batteries-charging', 'Battery Clamp / Terminal', 'battery-clamp-terminal', 40),
  ('ignition-system', 'Spark Plug', 'spark-plug', 10),
  ('ignition-system', 'Glow Plug', 'glow-plug', 20),
  ('ignition-system', 'Ignition Coil', 'ignition-coil', 30),
  ('ignition-system', 'Distributor Cap & Rotor', 'distributor-cap-rotor', 40),
  ('ignition-system', 'Ignition Lead Set', 'ignition-lead-set', 50),
  ('ignition-system', 'Ignition Module / Control Unit', 'ignition-module', 60),
  ('starter-alternator', 'Starter Motor', 'starter-motor', 10),
  ('starter-alternator', 'Starter Solenoid', 'starter-solenoid', 20),
  ('sensors-switches', 'Lambda / O2 Sensor', 'lambda-o2-sensor', 10),
  ('sensors-switches', 'MAF / Air Mass Sensor', 'maf-air-mass-sensor', 20),
  ('sensors-switches', 'MAP Sensor', 'map-sensor', 30),
  ('sensors-switches', 'Crankshaft Position Sensor', 'crankshaft-position-sensor', 40),
  ('sensors-switches', 'Camshaft Position Sensor', 'camshaft-position-sensor', 50),
  ('sensors-switches', 'Temperature Sensor (Coolant)', 'coolant-temperature-sensor', 60),
  ('sensors-switches', 'Oil Pressure Sensor / Switch', 'oil-pressure-sensor', 70),
  ('sensors-switches', 'Knock Sensor', 'knock-sensor', 80),
  ('sensors-switches', 'Throttle Position Sensor', 'throttle-position-sensor', 90),
  ('sensors-switches', 'Brake Light Switch', 'brake-light-switch', 100),
  ('sensors-switches', 'Clutch Switch', 'clutch-switch', 110),
  ('fuses-relays-wiring', 'Fuse Box / Fusible Link', 'fuse-box-fusible-link', 10),
  ('fuses-relays-wiring', 'Relay', 'relay', 20),
  ('fuses-relays-wiring', 'Wiring Loom / Harness', 'wiring-loom-harness', 30),
  ('cameras-parking-sensors', 'Reversing Camera', 'reversing-camera', 10),
  ('cameras-parking-sensors', 'Parking Sensor / PDC Sensor', 'parking-sensor-pdc', 20),
  ('catalytic-converters', 'Catalytic Converter', 'catalytic-converter', 10),
  ('catalytic-converters', 'Sport / High-Flow Cat', 'sport-high-flow-cat', 20),
  ('dpf-scr', 'Diesel Particulate Filter (DPF)', 'dpf', 10),
  ('dpf-scr', 'SCR Catalyst (AdBlue)', 'scr-catalyst-adblue', 20),
  ('dpf-scr', 'DPF Pressure Sensor', 'dpf-pressure-sensor', 30),
  ('exhaust-pipes-manifolds', 'Exhaust Manifold', 'exhaust-manifold', 10),
  ('exhaust-pipes-manifolds', 'Front / Mid Pipe', 'front-mid-pipe', 20),
  ('exhaust-pipes-manifolds', 'Downpipe', 'downpipe', 30),
  ('exhaust-pipes-manifolds', 'Cat-Back Exhaust System', 'cat-back-exhaust', 40),
  ('mufflers-silencers', 'Centre Silencer / Middle Box', 'centre-silencer', 10),
  ('mufflers-silencers', 'Rear Silencer / Back Box', 'rear-silencer', 20),
  ('mufflers-silencers', 'Exhaust Tip / Tail Pipe', 'exhaust-tip-tail-pipe', 30),
  ('exhaust-sensors', 'Pre-Cat Lambda Sensor', 'pre-cat-lambda-sensor', 10),
  ('exhaust-sensors', 'Post-Cat Lambda Sensor', 'post-cat-lambda-sensor', 20),
  ('exhaust-sensors', 'Exhaust Temperature Sensor', 'exhaust-temperature-sensor', 30),
  ('exhaust-clamps-hangers', 'Exhaust Clamp', 'exhaust-clamp', 10),
  ('exhaust-clamps-hangers', 'Exhaust Rubber Hanger / Mount', 'exhaust-rubber-hanger', 20),
  ('exhaust-clamps-hangers', 'Exhaust Flange Gasket', 'exhaust-flange-gasket', 30),
  ('radiators-intercoolers', 'Radiator', 'radiator', 10),
  ('radiators-intercoolers', 'Intercooler', 'intercooler-cooling', 20),
  ('radiators-intercoolers', 'Oil Cooler', 'oil-cooler', 30),
  ('radiators-intercoolers', 'EGR Cooler', 'egr-cooler-cooling', 40),
  ('cooling-fans-shrouds', 'Radiator Fan / Viscous Clutch Fan', 'radiator-fan', 10),
  ('cooling-fans-shrouds', 'Electric Cooling Fan', 'electric-cooling-fan', 20),
  ('cooling-fans-shrouds', 'Fan Shroud', 'fan-shroud', 30),
  ('cooling-fans-shrouds', 'Fan Coupling / Viscous Clutch', 'fan-coupling-viscous-clutch', 40),
  ('water-pumps-thermostats', 'Water Pump', 'water-pump', 10),
  ('water-pumps-thermostats', 'Thermostat', 'thermostat', 20),
  ('water-pumps-thermostats', 'Thermostat Housing', 'thermostat-housing', 30),
  ('water-pumps-thermostats', 'Expansion Tank / Coolant Reservoir', 'expansion-tank', 40),
  ('coolant-hoses-pipes', 'Radiator Hose (Upper)', 'radiator-hose-upper', 10),
  ('coolant-hoses-pipes', 'Radiator Hose (Lower)', 'radiator-hose-lower', 20),
  ('coolant-hoses-pipes', 'Heater Hose', 'heater-hose', 30),
  ('heater-core-blower', 'Heater Core / Matrix', 'heater-core-matrix', 10),
  ('heater-core-blower', 'Blower Motor / Heater Fan', 'blower-motor-heater-fan', 20),
  ('heater-core-blower', 'Heater Control Valve', 'heater-control-valve', 30),
  ('fuel-pumps', 'In-Tank Fuel Pump', 'in-tank-fuel-pump', 10),
  ('fuel-pumps', 'High-Pressure Fuel Pump (HPFP)', 'high-pressure-fuel-pump', 20),
  ('fuel-pumps', 'Lift Pump', 'lift-pump', 30),
  ('fuel-injectors-rails', 'Petrol Injector', 'petrol-injector', 10),
  ('fuel-injectors-rails', 'Diesel Injector', 'diesel-injector', 20),
  ('fuel-injectors-rails', 'Fuel Rail', 'fuel-rail', 30),
  ('fuel-injectors-rails', 'AdBlue / DEF Injector', 'adblue-def-injector', 40),
  ('fuel-tanks-caps', 'Fuel Tank', 'fuel-tank', 10),
  ('fuel-tanks-caps', 'Fuel Filler Cap', 'fuel-filler-cap', 20),
  ('fuel-tanks-caps', 'Fuel Tank Sender Unit', 'fuel-tank-sender-unit', 30),
  ('carburettors', 'Carburettor', 'carburettor', 10),
  ('carburettors', 'Carburettor Rebuild Kit', 'carburettor-rebuild-kit', 20),
  ('fuel-pressure-regulators', 'Fuel Pressure Regulator', 'fuel-pressure-regulator', 10),
  ('fuel-pressure-regulators', 'Fuel Pressure Sensor', 'fuel-pressure-sensor', 20),
  ('engine-filters', 'Oil Filter', 'oil-filter-cat', 10),
  ('engine-filters', 'Air Filter', 'air-filter-cat', 20),
  ('engine-filters', 'Fuel Filter', 'fuel-filter-cat', 30),
  ('engine-filters', 'Performance Air Filter / Cone', 'performance-air-filter', 40),
  ('engine-filters', 'Crankcase Breather Filter', 'crankcase-breather-filter', 50),
  ('cabin-interior-filters', 'Cabin Air Filter / Pollen Filter', 'cabin-air-filter', 10),
  ('cabin-interior-filters', 'Activated Carbon Cabin Filter', 'activated-carbon-cabin-filter', 20),
  ('tyres', 'Summer Tyre', 'summer-tyre', 10),
  ('tyres', 'Winter Tyre', 'winter-tyre', 20),
  ('tyres', 'All-Season Tyre', 'all-season-tyre', 30),
  ('tyres', 'Run-Flat Tyre', 'run-flat-tyre', 40),
  ('tyres', 'Off-Road / All-Terrain Tyre', 'off-road-all-terrain-tyre', 50),
  ('tyres', 'Van / Commercial Tyre', 'van-commercial-tyre', 60),
  ('alloy-steel-wheels', 'Alloy Wheel', 'alloy-wheel', 10),
  ('alloy-steel-wheels', 'Steel Wheel / Winter Wheel', 'steel-wheel-winter-wheel', 20),
  ('wheel-accessories', 'Wheel Bolt / Lug Nut', 'wheel-bolt-lug-nut', 10),
  ('wheel-accessories', 'Wheel Spacer', 'wheel-spacer', 20),
  ('wheel-accessories', 'Hub Centric Ring', 'hub-centric-ring', 30),
  ('wheel-accessories', 'Locking Wheel Nut Set', 'locking-wheel-nut-set', 40),
  ('wheel-accessories', 'Valve Stem', 'valve-stem', 50),
  ('tpms', 'TPMS Sensor', 'tpms-sensor', 10),
  ('tpms', 'TPMS Valve Stem', 'tpms-valve-stem', 20),
  ('headlights-front-lights', 'Headlight Assembly', 'headlight-assembly', 10),
  ('headlights-front-lights', 'Headlight Lens / Cover', 'headlight-lens-cover', 20),
  ('headlights-front-lights', 'DRL / LED Daytime Running Light', 'drl-daytime-running-light', 30),
  ('headlights-front-lights', 'Fog Light / Fog Lamp', 'fog-light-fog-lamp', 40),
  ('headlights-front-lights', 'Turn Signal / Indicator Front', 'turn-signal-indicator-front', 50),
  ('headlights-front-lights', 'Headlight Washer', 'headlight-washer', 60),
  ('headlights-front-lights', 'Headlight Levelling Motor', 'headlight-levelling-motor', 70),
  ('rear-brake-lights', 'Rear Light / Tail Light Assembly', 'rear-tail-light-assembly', 10),
  ('rear-brake-lights', 'Brake Light / Stop Light', 'brake-light-stop-light', 20),
  ('rear-brake-lights', 'Reverse Light', 'reverse-light', 30),
  ('rear-brake-lights', 'Turn Signal / Indicator Rear', 'turn-signal-indicator-rear', 40),
  ('rear-brake-lights', 'High Mount Stop Light (HMSL)', 'high-mount-stop-light', 50),
  ('rear-brake-lights', 'Number Plate Light', 'number-plate-light', 60),
  ('interior-lighting', 'Dome / Courtesy Light', 'dome-courtesy-light', 10),
  ('interior-lighting', 'Reading Light', 'reading-light', 20),
  ('interior-lighting', 'Boot / Trunk Light', 'boot-trunk-light', 30),
  ('bulbs', 'Halogen Bulb H1/H4/H7', 'halogen-bulb', 10),
  ('bulbs', 'HID / Xenon Bulb', 'hid-xenon-bulb', 20),
  ('bulbs', 'LED Bulb (retrofit)', 'led-bulb-retrofit', 30),
  ('bulbs', 'Indicator / Wedge Bulb', 'indicator-wedge-bulb', 40),
  ('light-control-switches', 'Headlight Switch', 'headlight-switch', 10),
  ('light-control-switches', 'Xenon / AFS Control Unit', 'xenon-afs-control-unit', 20),
  ('wiper-blades', 'Front Wiper Blade', 'front-wiper-blade', 10),
  ('wiper-blades', 'Rear Wiper Blade', 'rear-wiper-blade', 20),
  ('wiper-blades', 'Flat / Aero Wiper Blade', 'flat-aero-wiper-blade', 30),
  ('wiper-arms-linkages', 'Front Wiper Arm', 'front-wiper-arm', 10),
  ('wiper-arms-linkages', 'Rear Wiper Arm', 'rear-wiper-arm', 20),
  ('wiper-arms-linkages', 'Wiper Linkage', 'wiper-linkage', 30),
  ('wiper-arms-linkages', 'Wiper Motor', 'wiper-motor', 40),
  ('washer-pumps-jets', 'Windscreen Washer Pump', 'windscreen-washer-pump', 10),
  ('washer-pumps-jets', 'Washer Jet / Nozzle', 'washer-jet-nozzle', 20),
  ('washer-pumps-jets', 'Headlight Washer Pump', 'headlight-washer-pump', 30),
  ('washer-fluid-reservoirs', 'Washer Fluid Reservoir', 'washer-fluid-reservoir', 10),
  ('ac-compressors', 'AC Compressor', 'ac-compressor', 10),
  ('ac-compressors', 'AC Compressor Clutch', 'ac-compressor-clutch', 20),
  ('ac-condensers-evaporators', 'AC Condenser', 'ac-condenser', 10),
  ('ac-condensers-evaporators', 'AC Evaporator', 'ac-evaporator', 20),
  ('ac-condensers-evaporators', 'Receiver Drier / Dryer', 'receiver-drier-dryer', 30),
  ('ac-hoses-valves', 'AC Hose / Pipe', 'ac-hose-pipe', 10),
  ('ac-hoses-valves', 'Expansion Valve / Block Valve', 'expansion-valve-block-valve', 20),
  ('ac-hoses-valves', 'AC Pressure Switch', 'ac-pressure-switch', 30),
  ('cabin-air-filters-ac', 'Cabin Filter (Particulate)', 'cabin-filter-particulate', 10),
  ('cabin-air-filters-ac', 'Cabin Filter (Activated Carbon)', 'cabin-filter-carbon-ac', 20),
  ('bumpers-grilles', 'Front Bumper', 'front-bumper', 10),
  ('bumpers-grilles', 'Rear Bumper', 'rear-bumper', 20),
  ('bumpers-grilles', 'Front Grille', 'front-grille', 30),
  ('bumpers-grilles', 'Bumper Bracket / Support', 'bumper-bracket-support', 40),
  ('bonnets-doors', 'Bonnet / Hood', 'bonnet-hood', 10),
  ('bonnets-doors', 'Door', 'door', 20),
  ('bonnets-doors', 'Boot Lid / Tailgate', 'boot-lid-tailgate', 30),
  ('bonnets-doors', 'Bonnet Hinge', 'bonnet-hinge', 40),
  ('bonnets-doors', 'Bonnet Lock / Latch', 'bonnet-lock-latch', 50),
  ('bonnets-doors', 'Boot Gas Strut', 'boot-gas-strut', 60),
  ('wings-side-panels', 'Front Wing / Fender', 'front-wing-fender', 10),
  ('wings-side-panels', 'Side Skirt / Sill Cover', 'side-skirt-sill-cover', 20),
  ('mirrors', 'Wing Mirror / Door Mirror Assembly', 'wing-mirror-assembly', 10),
  ('mirrors', 'Mirror Glass', 'mirror-glass', 20),
  ('mirrors', 'Mirror Housing', 'mirror-housing', 30),
  ('mirrors', 'Blind Spot Mirror', 'blind-spot-mirror', 40),
  ('glass-seals', 'Windscreen / Windshield', 'windscreen-windshield', 10),
  ('glass-seals', 'Rear Window Glass', 'rear-window-glass', 20),
  ('glass-seals', 'Door Window Glass', 'door-window-glass', 30),
  ('glass-seals', 'Window Seal / Rubber', 'window-seal-rubber', 40),
  ('glass-seals', 'Window Regulator / Motor', 'window-regulator-motor', 50),
  ('roof-sunroof', 'Sunroof Glass', 'sunroof-glass', 10),
  ('roof-sunroof', 'Sunroof Motor & Mechanism', 'sunroof-motor-mechanism', 20),
  ('roof-sunroof', 'Roof Antenna', 'roof-antenna', 30),
  ('tow-bars-hitches', 'Tow Bar / Trailer Hitch', 'tow-bar-trailer-hitch', 10),
  ('tow-bars-hitches', 'Tow Ball', 'tow-ball', 20),
  ('tow-bars-hitches', 'Trailer Wiring Harness', 'trailer-wiring-harness', 30),
  ('paint-rustproofing', 'Touch-Up Paint', 'touch-up-paint', 10),
  ('paint-rustproofing', 'Stone Chip Paint / Underbody Seal', 'stone-chip-underbody-seal', 20),
  ('paint-rustproofing', 'Rust Converter / Inhibitor', 'rust-converter-inhibitor', 30),
  ('seats-upholstery', 'Seat Cover', 'seat-cover', 10),
  ('seats-upholstery', 'Seat Belt', 'seat-belt', 20),
  ('seats-upholstery', 'Seat Rail / Slider', 'seat-rail-slider', 30),
  ('dashboard-trim', 'Dashboard Panel', 'dashboard-panel', 10),
  ('dashboard-trim', 'Centre Console', 'centre-console', 20),
  ('dashboard-trim', 'Gear Knob', 'gear-knob', 30),
  ('dashboard-trim', 'Steering Wheel', 'steering-wheel', 40),
  ('pedals-floor-mats', 'Floor Mat Set', 'floor-mat-set', 10),
  ('pedals-floor-mats', 'Accelerator Pedal', 'accelerator-pedal', 20),
  ('pedals-floor-mats', 'Brake Pedal Pad', 'brake-pedal-pad', 30),
  ('seatbelts-airbags', 'Seatbelt Pretensioner', 'seatbelt-pretensioner', 10),
  ('seatbelts-airbags', 'Airbag Module', 'airbag-module', 20),
  ('seatbelts-airbags', 'Airbag Clock Spring', 'airbag-clock-spring', 30),
  ('door-handles-locks', 'Outer Door Handle', 'outer-door-handle', 10),
  ('door-handles-locks', 'Inner Door Handle', 'inner-door-handle', 20),
  ('door-handles-locks', 'Door Lock Actuator', 'door-lock-actuator', 30),
  ('door-handles-locks', 'Central Locking Pump', 'central-locking-pump', 40),
  ('service-kits', 'Major Service Kit', 'major-service-kit', 10),
  ('service-kits', 'Minor Service Kit', 'minor-service-kit', 20),
  ('service-kits', 'Timing Belt + Water Pump Kit', 'timing-belt-water-pump-kit', 30),
  ('service-kits', 'Cam Chain Service Kit', 'cam-chain-service-kit', 40),
  ('service-kits', 'Brake Service Kit', 'brake-service-kit', 50),
  ('engine-oil', 'Fully Synthetic Engine Oil', 'fully-synthetic-engine-oil', 10),
  ('engine-oil', 'Semi-Synthetic Engine Oil', 'semi-synthetic-engine-oil', 20),
  ('engine-oil', 'Mineral Engine Oil', 'mineral-engine-oil', 30),
  ('greases-lubricants', 'Multi-Purpose Grease', 'multi-purpose-grease', 10),
  ('greases-lubricants', 'Copper Grease', 'copper-grease', 20),
  ('greases-lubricants', 'Spray Lubricant (WD-40 type)', 'spray-lubricant', 30),
  ('greases-lubricants', 'Silicone Grease / Spray', 'silicone-grease-spray', 40),
  ('additives-treatments', 'Engine Oil Additive', 'engine-oil-additive', 10),
  ('additives-treatments', 'Fuel System Cleaner', 'fuel-system-cleaner', 20),
  ('additives-treatments', 'DPF Cleaner / Regenerator', 'dpf-cleaner-regenerator', 30),
  ('additives-treatments', 'Injector Cleaner', 'injector-cleaner', 40),
  ('additives-treatments', 'Coolant Additive', 'coolant-additive', 50),
  ('additives-treatments', 'Brake Fluid Tester', 'brake-fluid-tester', 60),
  ('diagnostic-tools', 'OBD2 Scanner / Code Reader', 'obd2-scanner-code-reader', 10),
  ('diagnostic-tools', 'Battery Tester / Analyser', 'battery-tester-analyser', 20),
  ('diagnostic-tools', 'Tyre Inflator / Compressor', 'tyre-inflator-compressor', 30),
  ('diagnostic-tools', 'Torque Wrench', 'torque-wrench', 40),
  ('diagnostic-tools', 'Jack & Jack Stands', 'jack-stands', 50)
) as v(parent_slug, name, slug, sort_order)
on p.slug = v.parent_slug
on conflict (slug) do update set
  parent_id = excluded.parent_id,
  name = excluded.name,
  level = excluded.level,
  sort_order = excluded.sort_order,
  updated_at = now();
